INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (31, 'Santa Catarina', 'São José', 'President Kenedi', 231, 7);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (32, 'Santa Catarina', 'Floripa', 'Rua das Joaninhas', 6312, 8);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (33, 'Santa Catarina', 'Floripa', 'Partida', 1231, null);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (34, 'Santa Catarina', 'Biguaçu', 'Chegada', 2312, null);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (35, 'Santa Catarina', 'Floripa', 'Rua', 231, 9);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (37, '1', '1', '1', 1, 11);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (38, '1', '1', '11', 1, 12);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (39, 'SC', 'Floripa', '1', 1, 13);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (40, '1', '2', '1', 1, null);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (41, '1', '1', '1', 1, null);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (42, '1', '1', '1', 1, null);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (43, '2', '2', '1', 2, null);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (44, '1', '1', '11', 1, null);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (45, '2', '2', '1', 2, null);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (46, '1', '1', '1', 1, null);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (47, '2', '2', '1', 2, null);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (48, '1', '1', '1', 1, null);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (49, '2', '2', '1', 22, null);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (50, '1', '1', '12', 2, null);
INSERT INTO cargapesada.address (address_id, state, city, street, number, user_id) VALUES (51, '2', '2', '2', 2, null);